/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Filter, Filter, 2)


PB_BIND(Value_setting, Value_setting, AUTO)


PB_BIND(Comparator, Comparator, AUTO)


PB_BIND(Field_value_pair, Field_value_pair, AUTO)


PB_BIND(Query_tree, Query_tree, 4)


PB_BIND(Return_code, Return_code, AUTO)


PB_BIND(Attribute, Attribute, AUTO)


PB_BIND(Entity, Entity, 2)



